class CfgUnitInsignia {
    MACRO_UNITINSIGNIA(Doge);
    MACRO_UNITINSIGNIA(Emeritus);
    MACRO_UNITINSIGNIA(Homokomando);
    MACRO_UNITINSIGNIA(King);
    MACRO_UNITINSIGNIA(Logo);
    MACRO_UNITINSIGNIA(Meal);
    MACRO_UNITINSIGNIA(Michus);
    MACRO_UNITINSIGNIA(Obajtek);
    MACRO_UNITINSIGNIA(Powidz);
    MACRO_UNITINSIGNIA(Resurs);
    MACRO_UNITINSIGNIA(Terror);

};
