name = "IBC"
prefix = "ibc"
author = "MiszczuZPolski"
mainprefix = "z"


[files]
include = [
    "mod.cpp",
    "README.md",
    "LICENSE.md",
    "ibc_logo.paa"
]

[version]
git_hash = 0


[hemtt.launch.default]
workshop = [
    "450814997", # CBA_A3's Workshop ID
    "463939057", # ACE3's Workshop ID
]
