name = "IBC"
prefix = "ibc"
author = "MiszczuZPolski"
mainprefix = "z"


[files]
include = [
    "mod.cpp",
    "README.md",
    "LICENSE.md",
    "ibc_logo.paa",
    "ibc_mods_x64.dll",
]

[version]
git_hash = 0
